### ISSUE TITLE
CordovaSQLiteDriver is not imported correctly when using  jsnext:main resolution in webpack

### ISSUE THREAD

**Issue by bdirito** [ionic-team/ionic-storage#163]
in ionic-storage.js (fesm2015) we have 
```
import * as CordovaSQLiteDriver from 'localforage-cordovasqlitedriver';
```
localforage-cordovasqlitedriver's package.json has a `jsnext:main` field. In there it has
```
export default cordovaSQLiteDriver;
```

The problem then is `*` is the file at large ie something of form `{default: cordovaSQLiteDriver}`. In contrast  when we run `defineDriver(CordovaSQLiteDriver)` its expecting the [default dereferenced] cordovaSQLiteDriver. This in turn causes a 
```
core.js:1971 ERROR Error: Uncaught (in promise): Error: Custom driver not compliant; see https://mozilla.github.io/localForage/#definedriver
Error: Custom driver not compliant; see https://mozilla.github.io/localForage/#definedriver
    at eval (localforage.js:2573)
```

While babel 5 had a shim to alias the default export to the module itself this is not part of the es6 spec. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import The import should be 
```
import CordovaSQLiteDriver from 'localforage-cordovasqlitedriver';
```
to be esm compatable.

Current workarround is aliasing 'localforage-cordovasqlitedriver' to the non es6 version in webpack.config[.coffee]
```
module.exports = 
   resolve:
      mainFields: ['module', 'jsnext:main', 'browser', 'main'] # note the normal pref for 'jsnext:main' over 'main'
      alias:
         'localforage-cordovasqlitedriver': path.resolve(__dirname, './node_modules/localforage-cordovasqlitedriver/dist/localforage-cordovasqlitedriver')
```
